-- 0021_talks_events.sql
-- Talks/panels/pitches of the current exhibition, crawled from the event
-- platform (talksiran.com) by scripts/train/talksiran_crawl.py and loaded by
-- scripts/train/import_talks_events.py. Served deterministically by the
-- events section of app/services/guide.py — no retrieval, no AI. An empty
-- table leaves that tier inert, so the migration can ship before the import.
CREATE TABLE IF NOT EXISTS app.talks_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   INTEGER NOT NULL UNIQUE,
    etype       TEXT NOT NULL DEFAULT '',
    title       TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    jdate       TEXT NOT NULL DEFAULT '',
    start_time  TEXT NOT NULL DEFAULT '',
    hall        TEXT NOT NULL DEFAULT '',
    members     TEXT NOT NULL DEFAULT '',
    url         TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_talks_events_jdate ON app.talks_events(jdate);
CREATE INDEX IF NOT EXISTS ix_talks_events_etype ON app.talks_events(etype);
