-- Padyar initial PostgreSQL schema.
--
-- Derived from the live SQLite contract, with types corrected rather than
-- copied: SQLite stored every timestamp as TEXT and every boolean as 0/1.
-- Carrying that into PostgreSQL would reproduce the limitation we are
-- migrating away from, so timestamps become TIMESTAMPTZ, flags become BOOLEAN
-- and log metadata becomes JSONB.
--
-- Two schemas keep the separation the SQLite deployment achieved with two
-- files: application data must not be slowed by log write volume.

BEGIN;

CREATE TABLE IF NOT EXISTS app.schema_migrations (
    version     TEXT PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    checksum    TEXT NOT NULL DEFAULT ''
);

-- ── Application data ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS app.admins (
    username              TEXT PRIMARY KEY,
    password_hash         TEXT NOT NULL,
    salt                  TEXT NOT NULL DEFAULT '',
    security_question     TEXT DEFAULT '',
    security_answer_hash  TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS app.admin_sessions (
    token     TEXT PRIMARY KEY,
    username  TEXT NOT NULL REFERENCES app.admins(username) ON DELETE CASCADE,
    expiry    TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_username ON app.admin_sessions(username);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_expiry   ON app.admin_sessions(expiry);

CREATE TABLE IF NOT EXISTS app.settings (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS app.dataset (
    id         TEXT PRIMARY KEY,
    title      TEXT NOT NULL DEFAULT '',
    text       TEXT NOT NULL DEFAULT '',
    video_url  TEXT NOT NULL DEFAULT '',
    title_en   TEXT NOT NULL DEFAULT '',
    text_en    TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS app.questions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question     TEXT NOT NULL,
    dataset_id   TEXT NOT NULL,
    video_url    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_questions_dataset ON app.questions(dataset_id);

-- Column names taken from the LIVE table, not from the documentation:
-- the real schema is (source, target) with no surrogate key.
CREATE TABLE IF NOT EXISTS app.synonyms (
    source  TEXT NOT NULL,
    target  TEXT NOT NULL,
    PRIMARY KEY (source, target)
);
CREATE INDEX IF NOT EXISTS ix_synonyms_source ON app.synonyms(source);

CREATE TABLE IF NOT EXISTS app.chat_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query          TEXT NOT NULL DEFAULT '',
    response       TEXT NOT NULL DEFAULT '',
    response_type  TEXT NOT NULL DEFAULT '',
    source         TEXT NOT NULL DEFAULT '',
    confidence     DOUBLE PRECISION,
    tokens         INTEGER,
    cost           NUMERIC(12, 6),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_chat_logs_created ON app.chat_logs(created_at DESC);

CREATE TABLE IF NOT EXISTS app.otp_challenges (
    id           TEXT PRIMARY KEY,
    destination  TEXT NOT NULL,
    code_hmac    TEXT NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    attempts     INTEGER NOT NULL DEFAULT 0,
    resends      INTEGER NOT NULL DEFAULT 0,
    used         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_sent_at TIMESTAMPTZ,
    first_name   TEXT NOT NULL DEFAULT '',
    last_name    TEXT NOT NULL DEFAULT '',
    job          TEXT NOT NULL DEFAULT '',
    position     TEXT NOT NULL DEFAULT '',
    interests    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_otp_destination ON app.otp_challenges(destination, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_otp_expires     ON app.otp_challenges(expires_at);

-- Persistent brute-force state. In SQLite this lived in a module-level dict,
-- so a restart cleared it — an attacker only had to wait for a deploy.
CREATE TABLE IF NOT EXISTS app.login_attempts (
    ip            TEXT PRIMARY KEY,
    attempts      INTEGER NOT NULL DEFAULT 0,
    block_until   TIMESTAMPTZ,
    last_attempt  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMIT;
