-- Observability schema.
--
-- One shared column set across four tables, matching the SQLite design so the
-- existing query/export/detail code needs no reshaping. Two deliberate type
-- upgrades over SQLite:
--
--   created_at  TEXT  -> TIMESTAMPTZ   (real time arithmetic for retention)
--   metadata    TEXT  -> JSONB         (queryable; no re-parsing in Python)
--
-- Partitioning was considered and NOT applied. The live log tables hold zero
-- rows today and retention is 90/365 days; range partitioning would add
-- partition-creation machinery and a failure mode for no present benefit.
-- Revisit when app_logs sustains millions of rows — the schema is compatible
-- with converting to a partitioned parent later.

BEGIN;

CREATE OR REPLACE FUNCTION observability.noop() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['app_logs','audit_logs','security_events','service_events'] LOOP
    EXECUTE format($f$
      CREATE TABLE IF NOT EXISTS observability.%I (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
          level           TEXT NOT NULL DEFAULT 'info',
          category        TEXT NOT NULL DEFAULT 'system',
          subcategory     TEXT NOT NULL DEFAULT '',
          event_name      TEXT NOT NULL DEFAULT '',
          message         TEXT NOT NULL DEFAULT '',
          outcome         TEXT NOT NULL DEFAULT '',
          actor           TEXT NOT NULL DEFAULT '',
          actor_type      TEXT NOT NULL DEFAULT '',
          target          TEXT NOT NULL DEFAULT '',
          ip              TEXT NOT NULL DEFAULT '',
          user_agent      TEXT NOT NULL DEFAULT '',
          provider        TEXT NOT NULL DEFAULT '',
          model           TEXT NOT NULL DEFAULT '',
          route           TEXT NOT NULL DEFAULT '',
          http_method     TEXT NOT NULL DEFAULT '',
          http_status     INTEGER,
          duration_ms     INTEGER,
          tokens_in       INTEGER,
          tokens_out      INTEGER,
          cost            NUMERIC(12, 6),
          retry_count     INTEGER,
          error_type      TEXT NOT NULL DEFAULT '',
          error_code      TEXT NOT NULL DEFAULT '',
          stack           TEXT NOT NULL DEFAULT '',
          request_id      TEXT NOT NULL DEFAULT '',
          correlation_id  TEXT NOT NULL DEFAULT '',
          conversation_id TEXT NOT NULL DEFAULT '',
          metadata        JSONB
      )$f$, t);

    -- Indexes chosen from the queries the admin UI actually issues: newest
    -- first paging, per-category paging, severity filtering, and the three
    -- correlation lookups. No more — every index costs write amplification on
    -- the hottest write path in the application.
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_created ON observability.%I(created_at DESC)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_cat     ON observability.%I(category, created_at DESC)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_level   ON observability.%I(level, created_at DESC)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_req     ON observability.%I(request_id)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_corr    ON observability.%I(correlation_id)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_conv    ON observability.%I(conversation_id)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_actor   ON observability.%I(actor, created_at DESC)', t, t);
  END LOOP;
END $$;

COMMIT;
