-- AI provider control plane.
--
-- Everything the Padyar AI Wrapper needs at runtime: provider instances and
-- their secrets, the per-instance model catalog, task routes with ordered
-- failover targets, shared circuit-breaker state, time-versioned pricing and
-- one usage row per wrapper call.
--
-- Shape decisions (from AI-PROVIDER-CHECKPOINT.md §6):
--
--   * Tables live in the existing `app` schema with an `ai_` prefix. A third
--     schema would require widening every query's search_path for no gain.
--   * Relational columns for anything the routing engine filters or orders on;
--     JSONB (`config`, `metadata`) only for genuinely provider-specific shape.
--     The per-adapter configuration_schema() defines what goes inside `config`
--     (base_url, region, workspace_id, platform, api_version, project...).
--   * NO secret material in JSONB. The single `secret_enc` column holds an
--     `enc:`-prefixed Fernet token produced by app/services/secure_store.py
--     (protect()/reveal()). It is never selected into an admin response.
--   * Model rows are scoped to a provider INSTANCE, not a provider type: the
--     same vendor type can exist as several instances with different catalogs
--     (enterprise gateway vs public gateway), and discovery is per instance.
--   * Pricing is time-versioned; the cost actually charged is ALSO stored on
--     the usage row, so a later price change cannot rewrite history.
--   * Circuit state lives here, not in process memory, so all workers agree.
--   * `ai_route_targets.priority` uniqueness is enforced non-deferrably; the
--     route store reorders atomically with a two-phase offset inside one
--     transaction (works identically on PostgreSQL and SQLite).
--
-- A byte-compatible SQLite DDL for the test suite lives in
-- app/services/ai/store.py:ensure_ai_tables() — tests run without PostgreSQL,
-- and the two definitions must stay in sync (same columns, same constraints).
--
-- NOTE: no BEGIN/COMMIT in this file. scripts/apply_migrations.py wraps each
-- migration in its own transaction (conn.transaction()); an explicit COMMIT
-- here would end the runner's transaction out from under its savepoint.

-- ── Provider instances ─────────────────────────────────────────────────
CREATE TABLE app.ai_provider_instances (
    id             TEXT PRIMARY KEY,            -- short slug, e.g. 'openai-main'
    provider_type  TEXT NOT NULL,               -- registry key: openai, anthropic, gemini, zai, kimi, deepseek, qwen, xai, mistral, openai_compatible
    display_name   TEXT NOT NULL,
    enabled        BOOLEAN NOT NULL DEFAULT FALSE,
    trust_class    TEXT NOT NULL DEFAULT 'public'
                   CHECK (trust_class IN ('public', 'internal')),
    config         JSONB NOT NULL DEFAULT '{}', -- provider-specific, schema owned by the adapter
    secret_enc     TEXT NOT NULL DEFAULT '',    -- enc:<fernet>; never returned by any admin API
    has_secret     BOOLEAN NOT NULL DEFAULT FALSE, -- computed on write, so listings never read secret_enc
    notes          TEXT NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     TEXT NOT NULL DEFAULT '',
    updated_by     TEXT NOT NULL DEFAULT ''
);

CREATE INDEX ix_ai_providers_type    ON app.ai_provider_instances(provider_type);
CREATE INDEX ix_ai_providers_enabled ON app.ai_provider_instances(enabled, provider_type);

-- ── Per-instance model catalog ─────────────────────────────────────────
CREATE TABLE app.ai_provider_models (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_instance_id  TEXT NOT NULL REFERENCES app.ai_provider_instances(id) ON DELETE CASCADE,
    model_id              TEXT NOT NULL,
    display_name          TEXT NOT NULL DEFAULT '',
    -- where the row came from; 'manual' rows are never touched by refresh
    source                TEXT NOT NULL DEFAULT 'bootstrap'
                          CHECK (source IN ('bootstrap', 'discovered', 'manual')),
    -- lifecycle; disappearing from discovery downgrades to 'unavailable',
    -- never deleted, so historical logs stay interpretable
    status                TEXT NOT NULL DEFAULT 'available'
                          CHECK (status IN ('available', 'preview', 'deprecated', 'legacy',
                                            'unavailable', 'unknown', 'manual')),
    supports_chat         BOOLEAN NOT NULL DEFAULT TRUE,
    supports_reasoning    BOOLEAN NOT NULL DEFAULT FALSE,
    supports_streaming    BOOLEAN NOT NULL DEFAULT TRUE,
    supports_tools        BOOLEAN NOT NULL DEFAULT FALSE,
    supports_structured   BOOLEAN NOT NULL DEFAULT FALSE,
    supports_vision       BOOLEAN NOT NULL DEFAULT FALSE,
    context_window        INTEGER,          -- NULL = unknown, never guessed
    max_output_tokens     INTEGER,
    metadata              JSONB,            -- provider-native extras (aliases, shutdown_date, effort levels...)
    metadata_refreshed_at TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider_instance_id, model_id)
);

CREATE INDEX ix_ai_models_instance ON app.ai_provider_models(provider_instance_id, status);

-- ── Task routes ────────────────────────────────────────────────────────
-- One row per routable task. Seeded tasks: 'chat', 'classify'.
CREATE TABLE app.ai_routes (
    task        TEXT PRIMARY KEY,
    description TEXT NOT NULL DEFAULT '',
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE app.ai_route_targets (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task                 TEXT NOT NULL REFERENCES app.ai_routes(task) ON DELETE CASCADE,
    provider_instance_id TEXT NOT NULL REFERENCES app.ai_provider_instances(id),
    model_id             TEXT NOT NULL,
    priority             INTEGER NOT NULL CHECK (priority > 0),  -- 1 = tried first
    enabled              BOOLEAN NOT NULL DEFAULT TRUE,
    max_attempts         INTEGER CHECK (max_attempts >= 1),      -- NULL = task default
    timeout_s            REAL,                                   -- NULL = task default
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (task, provider_instance_id, model_id),
    UNIQUE (task, priority)
);

CREATE INDEX ix_ai_route_targets_order ON app.ai_route_targets(task, priority);

-- ── Circuit breaker (shared across workers) ────────────────────────────
CREATE TABLE app.ai_circuit_state (
    provider_instance_id  TEXT PRIMARY KEY REFERENCES app.ai_provider_instances(id) ON DELETE CASCADE,
    state                 TEXT NOT NULL DEFAULT 'closed'
                          CHECK (state IN ('closed', 'open', 'half_open')),
    failure_count         INTEGER NOT NULL DEFAULT 0,
    window_started_at     TIMESTAMPTZ,
    last_failure_at       TIMESTAMPTZ,
    last_failure_code     TEXT NOT NULL DEFAULT '',
    last_success_at       TIMESTAMPTZ,
    opened_at             TIMESTAMPTZ,
    cooldown_until        TIMESTAMPTZ,
    -- half-open coordination: one worker wins a probe lease, the rest wait
    probe_owner           TEXT NOT NULL DEFAULT '',
    probe_expires_at      TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Time-versioned pricing ─────────────────────────────────────────────
CREATE TABLE app.ai_model_pricing (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_type             TEXT NOT NULL,
    model_id                  TEXT NOT NULL,
    currency                  TEXT NOT NULL DEFAULT 'USD',
    input_per_million         NUMERIC(12, 6) NOT NULL,
    cached_input_per_million  NUMERIC(12, 6),   -- NULL = no separate cached rate known
    output_per_million        NUMERIC(12, 6) NOT NULL,
    effective_from            TIMESTAMPTZ NOT NULL,
    source                    TEXT NOT NULL DEFAULT '',  -- e.g. 'bootstrap: research 2026-08-18'
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_ai_pricing_lookup
    ON app.ai_model_pricing(provider_type, model_id, effective_from DESC);

-- ── Usage: one row per wrapper call (not per attempt) ──────────────────
-- Per-attempt detail lives in observability.app_logs (llm.request.*). This
-- table is for aggregation: tokens/cost are SUMMED across attempts because
-- every attempt was billed; latency is the whole wrapper call.
CREATE TABLE app.ai_usage_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    task                 TEXT NOT NULL,
    status               TEXT NOT NULL CHECK (status IN ('success', 'failed')),
    provider_type        TEXT NOT NULL DEFAULT '',
    provider_instance_id TEXT NOT NULL DEFAULT '',
    model                TEXT NOT NULL DEFAULT '',
    attempts             INTEGER NOT NULL DEFAULT 1,
    failovers            INTEGER NOT NULL DEFAULT 0,
    tokens_in            INTEGER,
    tokens_out           INTEGER,
    tokens_cached        INTEGER,
    tokens_total         INTEGER,
    latency_ms           INTEGER,
    cost                 NUMERIC(12, 6),        -- NULL = pricing unknown; never guessed
    currency             TEXT NOT NULL DEFAULT '',
    pricing_effective_from TIMESTAMPTZ,         -- the price row used, for audit
    error_code           TEXT NOT NULL DEFAULT '',
    request_id           TEXT NOT NULL DEFAULT '',
    correlation_id       TEXT NOT NULL DEFAULT '',
    metadata             JSONB
);

CREATE INDEX ix_ai_usage_created   ON app.ai_usage_events(created_at DESC);
CREATE INDEX ix_ai_usage_provider  ON app.ai_usage_events(provider_instance_id, created_at DESC);
CREATE INDEX ix_ai_usage_task      ON app.ai_usage_events(task, created_at DESC);
CREATE INDEX ix_ai_usage_model     ON app.ai_usage_events(model, created_at DESC);

-- Seed the two Padyar tasks. Route TARGETS are created by the operator (or by
-- the legacy-config import), never seeded blind.
INSERT INTO app.ai_routes (task, description) VALUES
    ('chat',     'پاسخ‌دهی آزاد به پرسش‌های خارج از دانش‌بازه'),
    ('classify', 'دسته‌بندی نیت پرسش کاربر')
ON CONFLICT (task) DO NOTHING;
